---


# - name: Install dependencies
#   pip:
#     requirements: "{{ planet_source }}/requirements.txt"
#     virtualenv: "{{ planet_virtualenv }}"
#   when: server_mode == "production"


- name: Create config directory
  file: path={{ planet_config }} state=directory
  when: server_mode == "production"


- name: Create application config
  template: src=production.conf.j2 dest={{ planet_config }}/production.conf
  when: server_mode == "production"


- name: Add gunicorn config
  template: src=gunicorn.py.j2 dest={{ planet_config }}/gunicorn.py
  when: server_mode == "production"


- name: Add supervisor config
  template: src=supervisor.conf.j2 dest={{ supervisor_incdir }}/{{ planet_app_name }}.conf
  when: server_mode == "production"


- name: Add nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ planet_app_name }}.conf
  notify:
    - nginx restart