---

server_mode: production

planet_app_name: planet
planet_user: www-data
planet_server_name: planet.com

planet_base: /var/planet
planet_virtualenv: "{{ planet_base }}/venv"
planet_source: "{{planet_base}}/src"
planet_config: "{{ planet_base }}/config"
planet_public_dir: "{{ planet_base }}/public"

planet_bind: "127.0.0.1:9090"